import type { Metadata } from "next";
import React from "react";
import "./style/index.scss";
import Header from "./ui/layouts/Header";
import { inter } from "./utils/fonts";

export const metadata: Metadata = {
  title: "Corps et Ame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <React.Fragment>
          <Header />
          {children}
        </React.Fragment>
      </body>
    </html>
  );
}
