import type { Metadata } from "next";
import "./style/index.scss";

export const metadata: Metadata = {
  title: "Corps et Ame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  );
}
