import type { Metadata } from "next";
import React from "react";
import "./style/index.scss";
import Header from "./ui/layouts/Header";

export const metadata: Metadata = {
  title: "Corps et Ame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <link rel="preload" href="/assets/video.png" as="image" />
      </head>
      <body>
        <React.Fragment>
          <Header />
          {children}
        </React.Fragment>
      </body>
    </html>
  );
}
